/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package tennisgame.tennis;

import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lucho
 */
public class Tablero extends javax.swing.JFrame {

    /**
     * Creates new form Tablero
     */
    
    DefaultTableModel tablam;    
    String nombreJugador1;
    String nombreJugador2;
    int a;
    int b;
    String d[]=new String[3];
    public Tablero() {
        initComponents();
        JOptionPane.showMessageDialog(this,"Welcome to play tennis");
        nombre_Jugadores();
        tablam = new DefaultTableModel();
        tablam.addColumn(nombreJugador1);
        tablam.addColumn(nombreJugador2);
        tablam.addColumn("Score");
        this.jTable1.setModel(tablam);
    }
    
    
    public final void nombre_Jugadores(){
        nombreJugador1= JOptionPane.showInputDialog("Player Name 1", "Escribe tu nombre"); 
        nombreJugador2= JOptionPane.showInputDialog("Player Name 2", "Escribe el nombre de tu oponente");
    }  
    
     
    public void llenarTabla(String [] d){
        tablam.addRow(d);
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        String h;
        String j;
        String k;
        String f[]=new String[3];
        int row = jTable1.getSelectedRow();
            

        for(int z=tablam.getRowCount() -1; z>=row; z--){
        tablam.removeRow(z);
        }
        
        int t=tablam.getRowCount()-1;
         h=(f[0]=jTable1.getValueAt(t, 0).toString());
            j=(f[1]=jTable1.getValueAt(t, 1).toString());
            k=(f[2]=jTable1.getValueAt(t, 2).toString());
            a=Integer.parseInt(h);
            b=Integer.parseInt(j);
            d[0]=f[0];
            d[1]=f[1];
            d[2]=f[2];
            actualizarMarcador();
    }//GEN-LAST:event_jTable1MouseClicked
    
    public String [] actualizarMarcador(){
        return d;
    }
    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

}
